sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.12"

matrix:
  include:
    - node_js: "iojs"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      before_install:
          - export CXX="g++-4.8"

before_script:
  - if [ "`nvm current`" < "system" ]; then N=`which node`; D=`dirname $N`; ln -s $D/../lib/node_modules/npm/bin/node-gyp-bin/node-gyp; fi
